name: Notion Database Sync

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日深夜に実行
  workflow_dispatch:     # 手動実行も可能

jobs:
  sync-notion-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notion-client
      
      - name: Fetch Notion Database
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          python scripts/sync_notion.py
      
      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add notion_data.json
          git commit -m "Update Notion database data"
          git push
